<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class RedirectMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure(\Illuminate\Http\Request): (\Illuminate\Http\Response|\Illuminate\Http\RedirectResponse)  $next
     * @return \Illuminate\Http\Response|\Illuminate\Http\RedirectResponse
     */
    public function handle(Request $request, Closure $next)
    {
        $redirects = [
            // transport-services
            'services' => "transport-services",
            'services/car-shipping-service' => 'transport-services/car/',
            'services/motorcycle-shipping-service' => 'transport-services/motorcycle/',
            'services/atv-utv-transport' => 'transport-services/atv-utv/',
            'services/golf-cart-shipping-service' => 'transport-services/golf-cart/',
            'services/boat-service' => 'transport-services/boat/',
            'services/construction-equipment-transport-shipping' => 'transport-services/construction-equipment/',
            'services/commercial-truck-transport' => 'transport-services/commercial-truck/',
            'services/excavator-shipping-services' => 'transport-services/excavator/',
            'services/farm-transport-services' => 'transport-services/farm-equipment/',
            'services/heavy-equipment-shipping-services' => 'transport-services/heavy-equipment/',
            'services/rv-service' => 'transport-services/rv/',
            'services/dry-van-transportation' => 'transport-services/dry-van/',
            'services/hazmat-transport' => 'transport-services/hazmat/',
            'services/reefer-trucking' => 'transport-services/reefer/',
            'roro-shipping-international' => 'transport-services/roro/',
            // Auction Transport Services
            'auctions-car-transport' => 'auction-transport/car/',
            'heavy-auction-transport' => 'auction-transport/heavy-equipment/',
            '3pl-logistics' => 'auction-transport/freight/',            
            // Instant Quote Services
            'quote-form' => 'instant-quote/',
            'atv-utv' => 'instant-quote/atv-utv/',
            'farm_transport' => 'instant-quote/farm-equipment',
            'car' => 'instant-quote/car/',
            'golf-cart' => 'instant-quote/golf-cart/',
            'motorcycle' => 'instant-quote/motorcycle/',
            'boat' => 'instant-quote/boat/',
            'commercial-truck-transport' => 'instant-quote/commercial-truck/',
            'construction_transport' => 'instant-quote/construction-equipment/',
            'heavy' => 'instant-quote/heavy-equipment/',
            'excavator' => 'instant-quote/excavator/',
            'rv_transport' => 'instant-quote/rv/',
            'Hazmat-Transport' => 'instant-quote/hazmat/',
            'Dry-Van-Transport' => 'instant-quote/dry-van/',
            'Reefer-Shipping-Transport' => 'instant-quote/reefer/',
            'roro-shipping' => 'instant-quote/roro/',
            // public urls
            'public/heavy-equipment-hauling' => 'transport-services/heavy-equipment',
            'public/how-roro-transport-works' => 'transport-services/roro',
            'public/off-road-vehicle-shipping-in-california' => 'blog/off-road-vehicle-shipping-in-california',
            'public/quote-form' => 'instant-quote',
            'public/cheapest-car-shipping-service-cheap-car-transport' => 'blog/cheapest-car-shipping-service-cheap-car-transport',
            'public/ship-your-car-during-christmas-vacations' => 'blog/ship-your-car-during-christmas-vacations',
            'public/farm-tractor-transport' => 'blog/farm-tractor-transport',
            'public/how-are-oversized-vehicles-shipped' => 'blog/how-are-oversized-vehicles-shipped',
            'motorcycle?type=aVIvSVNNcHhLUnVPN2xqL29JeXFpQT09' => 'instant-quote/motorcycle',
            'public/utv-atv-shipping' => 'blog/utv-atv-shipping',
            'heavy?type=OXV4c01qTzl6UlBwdVRXR0JyMDdWZz09' => 'instant-quote/heavy-equipment',
            'public/blog/how-effective-auto-shipping-is-beneficial' => 'blog/how-effective-auto-shipping-is-beneficial',
            'heavy?type=NlBMOTRqVVdhSm1YTWMyS3FnQlhzQT09' => 'transport-services/heavy-equipment',
            'public/door-to-door-transport-delivery-vs-terminal-to-terminal-pick-up' => 'blog/door-to-door-transport-delivery-vs-terminal-to-terminal-pick-up',
            'public/blog/trailers-and-trucks-used-in-transportation' => 'blog',
            'public/privacy_policy' => 'inprivacy_policy', 
            'public/winter-vs--summer-auto-shipping' => 'blog/winter-vs--summer-auto-shipping',
            'public/vehicle-transport-service-from-california-to-delaware' => 'blog/vehicle-transport-service-from-california-to-delaware',
            'public/how-effective-auto-shipping-is-beneficial' => 'blog/how-effective-auto-shipping-is-beneficial',
            'public/contact_us' => 'contact_us',
            'public/blog/how-are-oversized-vehicles-shipped' => 'blog/how-are-oversized-vehicles-shipped',
            'public/order-form' => 'instant-quote',
            'public/door-to-door-transport-delivery-vs-terminal-to-terminal-pick-up' => 'blog/door-to-door-transport-delivery-vs-terminal-to-terminal-pick-up',
            'public/terms_and_conditions' => 'terms_and_conditions',
            'public/benefits-and-considerations-for-hiring-a-car-transport-company' => 'blog/benefits-and-considerations-for-hiring-a-car-transport-company',
            'public/order_tracking' => 'order_tracking',
            'public/maryland-to-new-york-car-shipping-services' => 'blog/maryland-to-new-york-car-shipping-services',
            'heavy?type=TU1sdi9xM1VtYTRtWjVZdHNkY1NFZz09' => 'instant-quote/heavy-equipment',
            'public/how-to-ship-a-reefer-truck' => 'blog/how-to-ship-a-reefer-truck',
            'public/california-to-colorado-car-transport-service' => 'blog/california-to-colorado-car-transport-service',
            'public/ship-gifted-vehicle-to-your-loved-one' => 'blog/ship-gifted-vehicle-to-your-loved-one',
            'public/how-to-ship-a-car-to-another-state' => 'blog/how-to-ship-a-car-to-another-state',
            'public/roro-shipping-service-in-the-united-states' => 'blog/roro-shipping-service-in-the-united-states',
            'public/international-vehicle-shipping-a-cost-comparison' => 'blog/international-vehicle-shipping-a-cost-comparison',
            'public/shipping-an-oversize-vehicle-from-virginia' => 'blog/shipping-an-oversize-vehicle-from-virginia',
            'public/answering-questions-about-shipping-a-non-running-vehicle' => 'blog/answering-questions-about-shipping-a-non-running-vehicle',
            'public/ultimate-guide-to-planning-car-shipping' => 'blog/ultimate-guide-to-planning-car-shipping',
            'public/how-season-affect-auto-shipping' => 'blog/how-season-affect-auto-shipping',
            'public/avoid-vehicle-shipping-scams' => 'blog/avoid-vehicle-shipping-scams',
            'public/why-auto-shipping-advantages-of-having-your-car-shipped-in-2019' => 'blog/why-auto-shipping-advantages-of-having-your-car-shipped-in-2019',
            'public/best-construction-equipment-transport-in-2019' => 'blog/best-construction-equipment-transport-in-2019',
            'public/shipping-your-motorcycle-the-smart-way-2019' => 'blog/shipping-your-motorcycle-the-smart-way-2019',
            'public/ultimate-guide-to-car-shipping-auto-shipping-ship-a1' => 'blog/ultimate-guide-to-car-shipping-auto-shipping-ship-a1',
            'public/how-accurate-is-an-online-car-shipping-calculator' => 'blog/how-accurate-is-an-online-car-shipping-calculator',
            'public/common-misconception-concerning-car-shipping' => 'blog/common-misconception-concerning-car-shipping',
            'public/what-is-the-benefits-of-shipping-farm-equipment-at-your-site' => 'blog/what-is-the-benefits-of-shipping-farm-equipment-at-your-site',
            'public/what-is-car-shipping-calculator' => 'blog/what-is-car-shipping-calculator',
            'public/ultimate-guide-to-motorcycle-shipping' => 'blog/ultimate-guide-to-motorcycle-shipping',
            'public/blog/ship-car-florida-to-california' => 'blog/ship-car-florida-to-california',
            'public/blog/top-reasons-state-to-state-auto-shippers-are-delayed' => 'blog/top-reasons-state-to-state-auto-shippers-are-delayed',
            'public/blog/door-to-door-transport-delivery-vs-terminal-to-terminal-pick-up' => 'blog/door-to-door-transport-delivery-vs-terminal-to-terminal-pick-up',
            'public/follow-these-steps-for-an-excellent-vehicle-inspection-report' => 'blog/follow-these-steps-for-an-excellent-vehicle-inspection-report',
            'public/blog/how-effective-auto-shipping-is-beneficial' => 'blog/how-effective-auto-shipping-is-beneficial',
            'public/blog/how-are-oversized-vehicles-shipped' => 'blog/how-are-oversized-vehicles-shipped',
            'public/shipping-luxury-vehicles-to-from-california' => 'blog/shipping-luxury-vehicles-to-from-california',
            'public/how-useful-to-roro-shipping-service' => 'blog/how-useful-to-roro-shipping-service',
            'heavy?type=cDB2Y3p0aHIvYWxyZ0M0aGprc01vUT09' => 'instant-quote/heavy-equipment',
            'public/blog/save-money-on-car-shipping' => 'blog/save-money-on-car-shipping',
            'public/blog/everything-to-know-about-shipping-a-car-from-state-to-state' => 'blog/everything-to-know-about-shipping-a-car-from-state-to-state',
            'public/door-to-door-shipping-service-in-new-mexico' => 'blog/door-to-door-shipping-service-in-new-mexico',
            'public/blog/auto-transport-terms-and-conditions' => 'blog/auto-transport-terms-and-conditions',
            'public/blog/how-to-ship-a-car-to-another-state1' => 'blog/how-to-ship-a-car-to-another-state1',
            'public/blog/criteria-for-evaluating-auto-transport-partner' => 'blog/criteria-for-evaluating-auto-transport-partner',
            'public/blog/car-shipping-cost-usa-negotiate-best-deal' => 'blog/car-shipping-cost-usa-negotiate-best-deal',
            'public/blog/state-to-state-auto-transport-affordable' => 'blog/state-to-state-auto-transport-affordable',
            'public/blog/ship-car-california-to-hawaii-shipa1' => 'blog/ship-car-california-to-hawaii-shipa1',
            'public/blog/expand-car-search-nationwide-shipping' => 'blog/expand-car-search-nationwide-shipping',
            'public/blog/luxury-car-state-to-state-auto-transport' => 'blog/luxury-car-state-to-state-auto-transport',
            'public/blog/what-is-state-to-state-car-shipping' => 'blog/what-is-state-to-state-car-shipping',
            'public/top-reasons-to-use-an-auto-transport-company' => 'blog/top-reasons-to-use-an-auto-transport-company',
            'public/start-this-new-decade-by-shipping-your-vehicle-with-ship-a1' => 'blog/start-this-new-decade-by-shipping-your-vehicle-with-ship-a1',
            'public/blog/how-to-ship-car-us-five-step-guide' => 'blog/how-to-ship-car-us-five-step-guide',
            'public/blog/cost-to-ship-car-florida-to-california' => 'blog/cost-to-ship-car-florida-to-california',
            'public/blog/how-state-to-state-auto-transport-works' => 'blog/how-state-to-state-auto-transport-works',
            'public/snowbird-car-shipping-guide' => 'blog/snowbird-car-shipping-guide',
            'public/blog/why-choose-state-to-state-auto-transport' => 'blog/why-choose-state-to-state-auto-transport',
            'public/blog/latest-trends-in-car-shipping-scams' => 'blog/latest-trends-in-car-shipping-scams',
            'public/blog/how-to-transfer-car-to-another-state' => 'blog/how-to-transfer-car-to-another-state',
            'public/blog/documents-required-to-ship-car-to-another-state' => 'blog/documents-required-to-ship-car-to-another-state',
            'public/blog/ask-for-relocation-assistance-auto-shippers' => 'blog/ask-for-relocation-assistance-auto-shippers',
            'public/blog/california-car-transport' => 'blog/california-car-transport',
            'public/know-your-vehicle-shipping-options' => 'blog/know-your-vehicle-shipping-options',
            'public/choosing-the-right-auto-shipping-company' => 'blog/choosing-the-right-auto-shipping-company',
            'public/future-of-auto-shipping-industry' => 'blog/future-of-auto-shipping-industry',
            'public/trends-that-will-transform-the-shipping-industry-in-the-future' => 'blog/trends-that-will-transform-the-shipping-industry-in-the-future',
            'public/why-florida-is-the-best-place-to-visit-during-december' => 'blog/why-florida-is-the-best-place-to-visit-during-december',
            'public/things-you-should-know-about-car-shipping-insurance' => 'blog/things-you-should-know-about-car-shipping-insurance',
            'public/benefits-of-shipping-your-vehicle-vs-hiring-a-driver' => 'blog/benefits-of-shipping-your-vehicle-vs-hiring-a-driver',
            'public/electric-car-shipping-services' => 'blog/electric-car-shipping-services',
            'public/signs-of-a-professional-shipping-service-fraud' => 'blog/signs-of-a-professional-shipping-service-fraud',
            'public/how-to-use-the-vehicle-shipping-calculator' => 'blog/how-to-use-the-vehicle-shipping-calculator',
            'public/shipping-a-car-to-or-from-las-vegas' => 'blog/shipping-a-car-to-or-from-las-vegas',
            'public/shipping-a-car-to-or-from-washington' => 'blog/shipping-a-car-to-or-from-washington',
            'public/car-shipping-services-in-montana' => 'blog/car-shipping-services-in-montana',
            'public/five-tips-before-shipping-your-sports-car-in-2020' => 'blog/five-tips-before-shipping-your-sports-car-in-2020',
            'public/shipping-a-car-from-los-angeles-to-new-york-city' => 'blog/shipping-a-car-from-los-angeles-to-new-york-city',
            'public/car-shipping-to-from-pennsylvania' => 'blog/car-shipping-to-from-pennsylvania',
            'public/finding-auto-shipping-services-in-baltimore' => 'blog/finding-auto-shipping-services-in-baltimore',
            'public/get-ready-for-exclusive-car-shipping-discount-on-christmas' => 'blog/get-ready-for-exclusive-car-shipping-discount-on-christmas',
            'public/how-much-does-enclosed-car-shipping-cost' => 'blog/how-much-does-enclosed-car-shipping-cost',
            'public/everything-you-need-to-know-about-minnesota-vehicle-transport' => 'blog/everything-you-need-to-know-about-minnesota-vehicle-transport',
            'public/guide-to-shipping-your-car-during-december' => 'blog/guide-to-shipping-your-car-during-december',
            'public/the-advantage-of-car-shipping-during-christmas-vacations' => 'blog/the-advantage-of-car-shipping-during-christmas-vacations',
            'public/auto-shipping-discount' => 'blog/auto-shipping-discount',
            'public/what-steps-to-follow-to-ship-your-car-now' => 'blog/what-steps-to-follow-to-ship-your-car-now',
            'public/how-much-does-it-cost-to-ship-a-vehicle-from-a-dealer' => 'blog/how-much-does-it-cost-to-ship-a-vehicle-from-a-dealer',
            'public/common-problems-associated-with-car-transport' => 'blog/common-problems-associated-with-car-transport',
            'public/how-door-to-door-car-shipping-is-affordable-and-convenient' => 'blog/how-door-to-door-car-shipping-is-affordable-and-convenient',
            'public/enjoy-a-stress-free-holiday-by-shipping-your-car-with-ship-a1' => 'blog/enjoy-a-stress-free-holiday-by-shipping-your-car-with-ship-a1',
            'public/why-you-should-get-a-professional-auto-transport-service' => 'blog/why-you-should-get-a-professional-auto-transport-service',
            'public/how-to-prepare-your-vehicle-for-shipping' => 'blog/how-to-prepare-your-vehicle-for-shipping',
            'public/the-most-important-vehicle-shipping-safety-tips' => 'blog/the-most-important-vehicle-shipping-safety-tips',
            'public/north-carolina-car-shipping-101--transporting-to-and-from-north-carolina' => 'blog/north-carolina-car-shipping-101--transporting-to-and-from-north-carolina',
            'public/what-to-expect-from-auto-transport-companies' => 'blog/what-to-expect-from-auto-transport-companies',
            'public/top-10-advantages-of-car-transport' => 'blog/top-10-advantages-of-car-transport',
            'public/virginia-auto-transport--shipping-to-virginia' => 'blog/virginia-auto-transport--shipping-to-virginia',
            'public/vermont-auto-transport--shipping-to-or-from-vermont' => 'blog/vermont-auto-transport--shipping-to-or-from-vermont',
            'public/shipping-an-automobile-to-or-from-connecticut' => 'blog/shipping-an-automobile-to-or-from-connecticut',
            'public/iowa-auto-shipping--shipping-to-or-from-iowa' => 'blog/iowa-auto-shipping--shipping-to-or-from-iowa',
            'public/door-to-door-car-shipping-suv-to-texas' => 'blog/door-to-door-car-shipping-suv-to-texas',
            'public/guide-to-shipping-a-truck' => 'blog/guide-to-shipping-a-truck',
            'public/top-affordable-vehicles-to-buy-in-2020' => 'blog/top-affordable-vehicles-to-buy-in-2020',
            'public/benefits-of-mini-excavator-shipping-at-your-construction-site' => 'blog/benefits-of-mini-excavator-shipping-at-your-construction-site',
            'public/ship-your-atv-utv-vehicle-from-california' => 'blog/ship-your-atv-utv-vehicle-from-california',
            'public/inoperable-vehicle-shipping-service-in-2020' => 'blog/inoperable-vehicle-shipping-service-in-2020',
            'public/blog/cost-to-move-vehicle-out-of-state' => 'blog/cost-to-move-vehicle-out-of-state',
            'public/prepare-your-modified-car-for-shipping-to-another-states' => 'blog/prepare-your-modified-car-for-shipping-to-another-states',
            'public/five-tips-to-improve-your-car-shipping-experience' => 'blog/five-tips-to-improve-your-car-shipping-experience',
            'public/auto-transport-service-from-maryland-to-florida' => 'blog/auto-transport-service-from-maryland-to-florida',
            'public/transport-your-car-from-maryland-to-california' => 'blog/transport-your-car-from-maryland-to-california',
            'public/blog/what-is-car-transport-service-why-people-want-this-type-of-services' => 'blog/how-to-ship-your-car-from-california-to-georgia',
            'public/transport-your-car-from-california-to-hawaii' => 'blog/transport-your-car-from-california-to-hawaii',
            'public/how-to-ship-your-car-from-california-to-georgia' => 'blog/how-to-ship-your-car-from-california-to-georgia',
            'public/tips-for-car-shipping-from-california-to-florida-' => 'blog/tips-for-car-shipping-from-california-to-florida-',
            'public/guide-to-shipping-a-car-with-an-enclosed-auto-transport-company' => 'blog/guide-to-shipping-a-car-with-an-enclosed-auto-transport-company',
            'public/blog?page=1' => 'blog?page=1',
            'public/car-shipping-carrier-service-from-florida-to-georgia' => 'blog/car-shipping-carrier-service-from-florida-to-georgia',
            'nationwide-autotransport/fatima-cook-1' => 'transport-services',
            'blog/trailers-and-trucks-used-in-transportation?page=1' => 'blog',
            'public/ultimate-guide-to-planning-car-shipping' => 'blog/ultimate-guide-to-planning-car-shipping',
            
            
            
              'heavy-equipment-hauling' => 'blog/heavy-equipment-hauling',
              'how-roro-transport-works' => 'blog/how-roro-transport-works',
              'off-road-vehicle-shipping-in-california' => 'blog/off-road-vehicle-shipping-in-california',
              'public/instant-quote' => '/instant-quote',
              'cheapest-car-shipping-service-cheap-car-transport' => 'blog/cheapest-car-shipping-service-cheap-car-transport',
              'ship-your-car-during-christmas-vacations' => 'blog/ship-your-car-during-christmas-vacations',
              'farm-tractor-transport' => 'blog/farm-tractor-transport',
              'how-are-oversized-vehicles-shipped' => 'blog/how-are-oversized-vehicles-shipped',
              'N/A' => 'instant-quote/motorcycle',
              'utv-atv-shipping' => 'blog/utv-atv-shipping',

              'N/A' => 'instant-quote/heavy-equipment',
              'how-effective-auto-shipping-is-beneficial' => 'blog/how-effective-auto-shipping-is-beneficial',
              'N/A' => 'transport-services/heavy-equipment',
              'door-to-door-transport-delivery-vs-terminal-to-terminal-pick-up' => 'blog/door-to-door-transport-delivery-vs-terminal-to-terminal-pick-up',
              'N/A' => 'blog',
              'winter-vs--summer-auto-shipping' => 'privacy_policy',
              'winter-vs--summer-auto-shipping' => 'blog/winter-vs--summer-auto-shipping',
              'vehicle-transport-service-from-california-to-delaware' => 'blog/vehicle-transport-service-from-california-to-delaware',
              'how-effective-auto-shipping-is-beneficial' => 'blog/how-effective-auto-shipping-is-beneficial',
              'N/A' => 'contact_us',

              'how-are-oversized-vehicles-shipped' => 'blog/how-are-oversized-vehicles-shipped',
              'N/A' => 'instant-quote',
              'door-to-door-transport-delivery-vs-terminal-to-terminal-pick-up' => 'blog/door-to-door-transport-delivery-vs-terminal-to-terminal-pick-up',
              'N/A' => 'terms_and_conditions',
              'benefits-and-considerations-for-hiring-a-car-transport-company' => 'blog/benefits-and-considerations-for-hiring-a-car-transport-company',
              'N/A' => 'order_tracking',
              'maryland-to-new-york-car-shipping-services' => 'blog/maryland-to-new-york-car-shipping-services',
              'N/A' => 'instant-quote/heavy-equipment',
              'how-to-ship-a-reefer-truck' => 'blog/how-to-ship-a-reefer-truck',
              'california-to-colorado-car-transport-service' => 'blog/california-to-colorado-car-transport-service',

              'ship-gifted-vehicle-to-your-loved-one' => 'blog/ship-gifted-vehicle-to-your-loved-one',
              'how-to-ship-a-car-to-another-state' => 'blog/how-to-ship-a-car-to-another-state',
              'roro-shipping-service-in-the-united-states' => 'blog/roro-shipping-service-in-the-united-states',
              'international-vehicle-shipping-a-cost-comparison' => 'blog/international-vehicle-shipping-a-cost-comparison',
              'shipping-an-oversize-vehicle-from-virginia' => 'blog/shipping-an-oversize-vehicle-from-virginia',
              'answering-questions-about-shipping-a-non-running-vehicle' => 'blog/answering-questions-about-shipping-a-non-running-vehicle',
              'ultimate-guide-to-planning-car-shipping' => 'blog/ultimate-guide-to-planning-car-shipping',
              'how-season-affect-auto-shipping' => 'blog/how-season-affect-auto-shipping',
              'avoid-vehicle-shipping-scams' => 'blog/avoid-vehicle-shipping-scams',
              'why-auto-shipping-advantages-of-having-your-car-shipped-in-2019' => 'blog/why-auto-shipping-advantages-of-having-your-car-shipped-in-2019',

              'best-construction-equipment-transport-in-2019' => 'blog/best-construction-equipment-transport-in-2019',
              'shipping-your-motorcycle-the-smart-way-2019' => 'blog/shipping-your-motorcycle-the-smart-way-2019',
              'ultimate-guide-to-car-shipping-auto-shipping-ship-a1' => 'blog/ultimate-guide-to-car-shipping-auto-shipping-ship-a1',
              'how-accurate-is-an-online-car-shipping-calculator' => 'blog/how-accurate-is-an-online-car-shipping-calculator',
              'common-misconception-concerning-car-shipping' => 'blog/common-misconception-concerning-car-shipping',
              'what-is-the-benefits-of-shipping-farm-equipment-at-your-site' => 'blog/what-is-the-benefits-of-shipping-farm-equipment-at-your-site',
              'what-is-car-shipping-calculator' => 'blog/what-is-car-shipping-calculator',
              'ultimate-guide-to-motorcycle-shipping' => 'blog/ultimate-guide-to-motorcycle-shipping',
              'ship-car-florida-to-california' => 'blog/ship-car-florida-to-california',
              'top-reasons-state-to-state-auto-shippers-are-delayed' => 'blog/top-reasons-state-to-state-auto-shippers-are-delayed',

              'door-to-door-transport-delivery-vs-terminal-to-terminal-pick-up' => 'blog/door-to-door-transport-delivery-vs-terminal-to-terminal-pick-up',
              'follow-these-steps-for-an-excellent-vehicle-inspection-report' => 'blog/follow-these-steps-for-an-excellent-vehicle-inspection-report',
              'how-effective-auto-shipping-is-beneficial' => 'blog/how-effective-auto-shipping-is-beneficial',
              'how-are-oversized-vehicles-shipped' => 'blog/how-are-oversized-vehicles-shipped',
              'shipping-luxury-vehicles-to-from-california' => 'blog/shipping-luxury-vehicles-to-from-california',
              'how-useful-to-roro-shipping-service' => 'blog/how-useful-to-roro-shipping-service',
              'N/A' => 'instant-quote/heavy-equipment',
              'save-money-on-car-shipping' => 'blog/save-money-on-car-shipping',
              'everything-to-know-about-shipping-a-car-from-state-to-state' => 'blog/everything-to-know-about-shipping-a-car-from-state-to-state',
              'door-to-door-shipping-service-in-new-mexico' => 'blog/door-to-door-shipping-service-in-new-mexico',

              'auto-transport-terms-and-conditions' => 'blog/auto-transport-terms-and-conditions',
              'how-to-ship-a-car-to-another-state1' => 'blog/how-to-ship-a-car-to-another-state1',
              'criteria-for-evaluating-auto-transport-partner' => 'blog/criteria-for-evaluating-auto-transport-partner',
              'car-shipping-cost-usa-negotiate-best-deal' => 'blog/car-shipping-cost-usa-negotiate-best-deal',
              'state-to-state-auto-transport-affordable' => 'blog/state-to-state-auto-transport-affordable',
              'ship-car-california-to-hawaii-shipa1' => 'blog/ship-car-california-to-hawaii-shipa1',
              'expand-car-search-nationwide-shipping' => 'blog/expand-car-search-nationwide-shipping',
              'luxury-car-state-to-state-auto-transport' => 'blog/luxury-car-state-to-state-auto-transport',
              'what-is-state-to-state-car-shipping' => 'blog/what-is-state-to-state-car-shipping',
              'top-reasons-to-use-an-auto-transport-company' => 'blog/top-reasons-to-use-an-auto-transport-company',

              'start-this-new-decade-by-shipping-your-vehicle-with-ship-a1' => 'blog/start-this-new-decade-by-shipping-your-vehicle-with-ship-a1',
              'how-to-ship-car-us-five-step-guide' => 'blog/how-to-ship-car-us-five-step-guide',
              'cost-to-ship-car-florida-to-california' => 'blog/cost-to-ship-car-florida-to-california',
              'how-state-to-state-auto-transport-works' => 'blog/how-state-to-state-auto-transport-works',
              'snowbird-car-shipping-guide' => 'blog/snowbird-car-shipping-guide',
              'why-choose-state-to-state-auto-transport' => 'blog/why-choose-state-to-state-auto-transport',
              'latest-trends-in-car-shipping-scams' => 'blog/latest-trends-in-car-shipping-scams',
              'how-to-transfer-car-to-another-state' => 'blog/how-to-transfer-car-to-another-state',
              'documents-required-to-ship-car-to-another-state' => 'blog/documents-required-to-ship-car-to-another-state',
              'ask-for-relocation-assistance-auto-shippers' => 'blog/ask-for-relocation-assistance-auto-shippers',

              'california-car-transport' => 'blog/california-car-transport',
              'know-your-vehicle-shipping-options' => 'blog/know-your-vehicle-shipping-options',
              'choosing-the-right-auto-shipping-company' => 'blog/choosing-the-right-auto-shipping-company',
              'future-of-auto-shipping-industry' => 'blog/future-of-auto-shipping-industry',
              'trends-that-will-transform-the-shipping-industry-in-the-future' => 'blog/trends-that-will-transform-the-shipping-industry-in-the-future',
              'why-florida-is-the-best-place-to-visit-during-december' => 'blog/why-florida-is-the-best-place-to-visit-during-december',
              'things-you-should-know-about-car-shipping-insurance' => 'blog/things-you-should-know-about-car-shipping-insurance',
              'benefits-of-shipping-your-vehicle-vs-hiring-a-driver' => 'blog/benefits-of-shipping-your-vehicle-vs-hiring-a-driver',
              'electric-car-shipping-services' => 'blog/electric-car-shipping-services',
              'signs-of-a-professional-shipping-service-fraud' => 'blog/signs-of-a-professional-shipping-service-fraud',

              'how-to-use-the-vehicle-shipping-calculator' => 'blog/how-to-use-the-vehicle-shipping-calculator',
              'shipping-a-car-to-or-from-las-vegas' => 'blog/shipping-a-car-to-or-from-las-vegas',
              'shipping-a-car-to-or-from-washington' => 'blog/shipping-a-car-to-or-from-washington',
              'car-shipping-services-in-montana' => 'blog/car-shipping-services-in-montana',
              'five-tips-before-shipping-your-sports-car-in-2020' => 'blog/five-tips-before-shipping-your-sports-car-in-2020',
              'shipping-a-car-from-los-angeles-to-new-york-city' => 'blog/shipping-a-car-from-los-angeles-to-new-york-city',
              'car-shipping-to-from-pennsylvania' => 'blog/car-shipping-to-from-pennsylvania',
              'finding-auto-shipping-services-in-baltimore' => 'blog/finding-auto-shipping-services-in-baltimore',
              'get-ready-for-exclusive-car-shipping-discount-on-christmas' => 'blog/get-ready-for-exclusive-car-shipping-discount-on-christmas',
              'how-much-does-enclosed-car-shipping-cost' => 'blog/how-much-does-enclosed-car-shipping-cost',

              'everything-you-need-to-know-about-minnesota-vehicle-transport' => 'blog/everything-you-need-to-know-about-minnesota-vehicle-transport',
              'guide-to-shipping-your-car-during-december' => 'blog/guide-to-shipping-your-car-during-december',
              'the-advantage-of-car-shipping-during-christmas-vacations' => 'blog/the-advantage-of-car-shipping-during-christmas-vacations',
              'auto-shipping-discount' => 'blog/auto-shipping-discount',
              'what-steps-to-follow-to-ship-your-car-now' => 'blog/what-steps-to-follow-to-ship-your-car-now',
              'how-much-does-it-cost-to-ship-a-vehicle-from-a-dealer' => 'blog/how-much-does-it-cost-to-ship-a-vehicle-from-a-dealer',
              'common-problems-associated-with-car-transport' => 'blog/common-problems-associated-with-car-transport',
              'how-door-to-door-car-shipping-is-affordable-and-convenient' => 'blog/how-door-to-door-car-shipping-is-affordable-and-convenient',
              'enjoy-a-stress-free-holiday-by-shipping-your-car-with-ship-a1' => 'blog/enjoy-a-stress-free-holiday-by-shipping-your-car-with-ship-a1',
              'why-you-should-get-a-professional-auto-transport-service' => 'blog/why-you-should-get-a-professional-auto-transport-service',
              'how-to-prepare-your-vehicle-for-shipping' => 'blog/how-to-prepare-your-vehicle-for-shipping',
              'the-most-important-vehicle-shipping-safety-tips' => 'blog/the-most-important-vehicle-shipping-safety-tips',
              'north-carolina-car-shipping-101--transporting-to-and-from-north-carolina' => 'blog/north-carolina-car-shipping-101--transporting-to-and-from-north-carolina',
              'what-to-expect-from-auto-transport-companies' => 'blog/what-to-expect-from-auto-transport-companies',
              'top-10-advantages-of-car-transport' => 'blog/top-10-advantages-of-car-transport',
              'virginia-auto-transport--shipping-to-virginia' => 'blog/virginia-auto-transport--shipping-to-virginia',
              'vermont-auto-transport--shipping-to-or-from-vermont' => 'blog/vermont-auto-transport--shipping-to-or-from-vermont',
              'shipping-an-automobile-to-or-from-connecticut' => 'blog/shipping-an-automobile-to-or-from-connecticut',
              'iowa-auto-shipping--shipping-to-or-from-iowa' => 'blog/iowa-auto-shipping--shipping-to-or-from-iowa',
              'door-to-door-car-shipping-suv-to-texas' => 'blog/door-to-door-car-shipping-suv-to-texas',

              'guide-to-shipping-a-truck' => 'blog/guide-to-shipping-a-truck',
              'top-affordable-vehicles-to-buy-in-2020' => 'blog/top-affordable-vehicles-to-buy-in-2020',
              'benefits-of-mini-excavator-shipping-at-your-construction-site' => 'blog/benefits-of-mini-excavator-shipping-at-your-construction-site',
              'ship-your-atv-utv-vehicle-from-california' => 'blog/ship-your-atv-utv-vehicle-from-california',
              'inoperable-vehicle-shipping-service-in-2020' => 'blog/inoperable-vehicle-shipping-service-in-2020',
              'cost-to-move-vehicle-out-of-state' => 'blog/cost-to-move-vehicle-out-of-state',
              'prepare-your-modified-car-for-shipping-to-another-states' => 'blog/prepare-your-modified-car-for-shipping-to-another-states',
              'five-tips-to-improve-your-car-shipping-experience' => 'blog/five-tips-to-improve-your-car-shipping-experience',
              'auto-transport-service-from-maryland-to-florida' => 'blog/auto-transport-service-from-maryland-to-florida',
              'transport-your-car-from-maryland-to-california' => 'blog/transport-your-car-from-maryland-to-california',
              'how-to-ship-your-car-from-california-to-georgia' => 'blog/how-to-ship-your-car-from-california-to-georgia',
              'transport-your-car-from-california-to-hawaii' => 'blog/transport-your-car-from-california-to-hawaii',
              'how-to-ship-your-car-from-california-to-georgia' => 'blog/how-to-ship-your-car-from-california-to-georgia',
              'tips-for-car-shipping-from-california-to-florida-' => 'blog/tips-for-car-shipping-from-california-to-florida-',
              'guide-to-shipping-a-car-with-an-enclosed-auto-transport-company' => 'blog/guide-to-shipping-a-car-with-an-enclosed-auto-transport-company',
              'N/A' => 'blog?page=1',
              'car-shipping-carrier-service-from-florida-to-georgia' => 'blog/car-shipping-carrier-service-from-florida-to-georgia',
              'N/A' => 'transport-services',
              'N/A' => 'blog',
              'ultimate-guide-to-planning-car-shipping/' => 'blog/ultimate-guide-to-planning-car-shipping',


            //   404 URLS
            'services/construction-equipment-shipping' => 'transport-services/construction-equipment',
            'vehicle-shipping-scam' => 'blog/avoid-vehicle-shipping-scams',
            'illinois-auto-transport-shipping-to-or-from-illinois' => 'blog/illinois-auto-transport--shipping-to-or-from-illinois',
            'about' => 'about_us',
            'motorcycle-shipping-service' => 'transport-services/motorcycle',
            'choosing-the-right-auto-shipping-company/' => 'blog/choosing-the-right-auto-shipping-company',
            'public/public/favicon.webp' => '/',
            'public/chat' => '/',
            'chat' => '/',
            'frieght' => 'transport-services/dry-van',
            'gifted-vehicle-shipping' => 'blog/ship-gifted-vehicle-to-your-loved-one',
            'north-carolina-car-shipping-101-transporting-to-and-from-north-carolina' => 'blog/north-carolina-car-shipping-101--transporting-to-and-from-north-carolina',
            'img/excavator-transportation.webp' => '/',
            'maryland-auto-transport-shipping-to-or-from-maryland' => 'blog/maryland-auto-transport--shipping-to-or-from-maryland',
            'services-overview' => 'transport-services',
            'what-is-the-best-time-of-the-year-to-ship-your-car' => 'blog/what-is-the-best-time-of-the-year-to-ship-your-car-',
            'img/banner-5-800x400-landing.webp' => '/',
            'exotic-car-shipping' => 'blog/exotic-car-shipping-in-florida',
            'why-auto-shipping-advantages-of-having-your-car-shipped-2019' => 'blog/why-auto-shipping-advantages-of-having-your-car-shipped-in-2019',
            'services/car-transport' => 'transport-services/car',
            'public/subscribe' => '/',
            'public/get-subcategories' => '/',
            'public/contact_messages' => '/',
            'public/get-zipcodes' => '/',
            'public/blog-details.html' => '/',
            'public/verifyEmail' => '/',
            'gifted-vehicle-shipping' => 'blog/ship-gifted-vehicle-to-your-loved-one',
            'quote/car' => 'instant-quote/car',
            'services/car-transport-service-expedited-shipping-service' => 'transport-services/car',
            'contact' => 'contact_us',
            'georgia-car-transport-shipping-to-or-from-georgia' => 'blog/georgia-car-transport--shipping-to-or-from-georgia',
            'farm-transport-in-2019' => 'blog/farm-tractor-transport',
            'what-is-the-most-efficient-way-to-ship-a-car-in-few-days' => 'blog/what-is-the-most-efficient-way-to-ship-a-car-in-few-days-',
            'nevada-vehicle-transport-shipping-to-or-from-nevada' => 'blog/nevada-vehicle-transport--shipping-to-or-from-nevada',
            'new-jersey-car-transport-shipping-to-or-from-new-jersey' => 'blog/new-jersey-car-transport--shipping-to-or-from-new-jersey',
            'heavy-equipment' => 'transport-services/heavy-equipment',
            'virginia-auto-transport-shipping-to-virginia' => 'blog/virginia-auto-transport--shipping-to-virginia',
            'dos-and-dont-of-shipping-an-inoperable-vehicle' => 'blog/do-s-and-don-t-of-shipping-an-inoperable-vehicle',
            'iowa-auto-shipping-shipping-to-or-from-iowa' => 'blog/iowa-auto-shipping--shipping-to-or-from-iowa',
            'services/heavy-equipment-transport' => 'transport-services/heavy-equipment',
            'expedited-shipping-service' => 'transport-services',
            'ohio-auto-transport-shipping-to-or-from-ohio' => 'blog/ohio-auto-transport--shipping-to-or-from-ohio',
            'blog_images/66aa9e4c0400c.webp' => '/',
            'car-shipping-to---from-pennsylvania' => 'blog/car-shipping-to-from-pennsylvania',
            'flatbed-trailers' => '/',
            'services/farm-transport' => 'transport-services/farm-equipment',
            'public/frontend/images/icon/flags.webp' => '/',
            'services/shipping-an-excavator' => 'transport-services/excavator',
            'heavy/type=OXV4c01qTzl6UlBwdVRXR0JyMDdWZz09' => '/',
            'frontend/images/project/auto-auction.webp' => '/',
            'trailers-and-trucks?page=3' => 'blog',
            'why-auto-shipping-advantages-of-having-a-car-shipping-company' => 'blog/top-10-advantages-of-car-transport',
            'shipping-a-car-from-los-angeles-to-new-york-city/1000' => 'blog/shipping-a-car-from-los-angeles-to-new-york-city',
            'ohio-auto-transport--shipping-to-or-from-ohio' => 'blog/ohio-auto-transport--shipping-to-or-from-ohio',
            'services/excavator-shipping-service' => 'transport-services/excavator',
            'trailers-and-trucks' => 'blog',
            'roro-shipping-international-service' => 'transport-services/roro',
            'do-s-and-don-t-of-shipping-an-inoperable-vehicle' => 'blog/do-s-and-don-t-of-shipping-an-inoperable-vehicle',
            'video' => '/',
            'heavy-duty-truck-transport' => 'transport-services/commercial-truck',
            'roro-shipping-in-united-states' => 'transport-services/roro',
            'tracking' => 'order_tracking',
            'auto_auction' => 'auction-transport/car',
            


        ];

        $currentPath = $request->path();

        if (array_key_exists($currentPath, $redirects)) {
            return redirect($redirects[$currentPath], 301);
        }

        return $next($request);
    }

}
